# Generated by Django 2.2 on 2019-04-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='default=False'),
            preserve_default=False,
        ),
    ]
